version: '3.8'
services:
  dev-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3drTCFvaKD
      - POSTGRES_DB=enyoblos
    ports:
      - 5432:5432